[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pyls"
version = "1.0.0"

[project.scripts]
pyls = "pyls.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
pyls = ["*.json"]